### ISSUE TITLE
Unable to instantiate SparkSession with Hive support because Hive classes are not found.

### ISSUE THREAD

**Issue by vonkonyoung** [vonkonyoung/myspark#3]
Unable to instantiate SparkSession with Hive support because Hive classes are not found.
Exception in thread "main" java.lang.IllegalArgumentException: Unable to instantiate SparkSession with Hive support because Hive classes are not found.
	at org.apache.spark.sql.SparkSession$Builder.enableHiveSupport(SparkSession.scala:871)
	at SparkSql_Hive$.main(SparkSql_Hive.scala:12)
	at SparkSql_Hive.main(SparkSql_Hive.scala)

**Comment by vonkonyoung** [comment]
看了很多的解答，说是版本一致性的问题，那要跟什么保持一致性呢？
先让spark-hive跟spark-core保持一致。
 <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.12</artifactId>
            <version>2.4.7</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.12</artifactId>
            <version>2.4.7</version>
        </dependency>

都弄成一样的了，好像不起作用啊。
